---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syringesa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syringerole
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syringe-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syringerole
subjects:
  - kind: ServiceAccount
    name: syringesa
    namespace: default

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: syringe
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  template: 
    metadata:
      name: syringe
      annotations:
        foobar: ""
      labels:
        app: syringe
        antidote_role: infra
    spec:
      serviceAccount: syringesa
      containers:
      - name: syringe
        image: antidotelabs/syringe:release-v0.3.0
        imagePullPolicy: Always
        env:
        - name: SYRINGE_DOMAIN
          value: "localhost:30002"
        - name: SYRINGE_LESSONS
          value: "/antidote/lessons"
        - name: SYRINGE_DOMAIN
          value: "localhost"
        - name: SYRINGE_TIER
          value: "local"
        - name: SYRINGE_LESSON_REPO_DIR
          value: "/antidote"
        - name: SYRINGE_LESSONS_LOCAL
          value: "true"
        ports:
        - containerPort: 50099  # GRPC
        - containerPort: 8086   # REST/HTTP
        volumeMounts:
          - mountPath: /antidote
            name: host-volume
      volumes:
        - name: host-volume
          hostPath:
            path: "/antidote"

---
kind: Service
apiVersion: v1
metadata:
  name: syringe
  namespace: default
spec:
  selector:
    app: syringe
  ports:
    - name: grpc
      port: 50099
      targetPort: 50099
      # nodePort: 30010
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-services: "syringe"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  name: syringe-ingress
  namespace: default
spec:
  tls:
    - hosts:
      - antidote-local
  rules:
  - host: "antidote-local"
    http:
      paths:
      - path: "/syringe"
        backend:
          serviceName: syringe
          servicePort: 8086

